### ISSUE TITLE
Download failed with no error

### ISSUE THREAD

**Issue by anthonylarbalestier** [pixolution/PixolutionImageDownloader#1]
Hi,

I'm running into an error where all my downloads are failing
There isn't enough information to troubleshoot

λ pxl_downloader --threads=8 download --tarfile --ratelimit-interval=2 --ratelimit-downloads=50 test_download_v2.csv C:\Users\anthony\Documents\ecommerce\content\PixolutionImageDownloader-master\output
set up RateLimiter:  50.0  actions per  2.0  seconds
start downloading of list C:\Users\anthony\Documents\ecommerce\content\PixolutionImageDownloader-master\test_download_v2.csv with 8 threads
store downloads into tar file: C:\Users\anthony
\Documents\ecommerce\content\PixolutionImageDownloader-master\output\test_download_v2.csv_images.tar
threadpool starts to download now
Processing finished:
Ok: 0  Fail: 1  Empty lines: 0  Skipped: 0 Total: 1 Running=0s Rate=77 #/s

resaved the file as a txt to attach
[test_download_v2.txt](https://github.com/pixolution/PixolutionImageDownloader/files/3581828/test_download_v2.txt)

[test_download_v2.csv_errors.log](https://github.com/pixolution/PixolutionImageDownloader/files/3581827/test_download_v2.csv_errors.log)

**Comment by sebastianlutter** [comment]
Thanks for your report!

I can download the image url in your csv list in my browser, but using python urllib fails with server code 403 (forbidden)

* When I try to run this minimal example with python3:
```
from urllib.parse import urlparse
import urllib.request

url="https://images.pexels.com/photos/356378/pexels-photo-356378.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
outfile="/tmp/fooo.jpeg"

urllib.request.urlretrieve(url,outfile)
```
* I get this error
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    urllib.request.urlretrieve(url,outfile)
  File "/usr/lib/python3.5/urllib/request.py", line 188, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

Maybe the server checks the browser signature of clients and tries to keep bots out. I need to further investigate this

**Comment by sebastianlutter** [comment]
I replaced **urllib.request.urlretrieve** (deprecated) with **requests.get** to download images. Please check if the problem is solved for you and close the ticket.

Some additional notes:
* you only get error messages on failed downloads when you set --verbose
* the errors file only contains the URLs of the failed files so you can inspect and re-download them, you will not get error messages in this file

**Comment by anthonylarbalestier** [comment]
Thanks for the change, the issue is resolved
